baseURL: https://bporter.net
languageCode: en-us
title: Benjamin Porter

params:
  tagline:
    - Software Engineer
    - Terraform Engineer
    - YAML Engineer
  emoji:
    - ğŸ“
    - ğŸŒ®
    - ğŸ»
    - ğŸˆ

enableGitInfo: true

disableKinds:
  - taxonomy
  - taxonomyTerm
